apiVersion : apps/v1
kind: Deployment
metadata:
  name: ranvijaysanumrepo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ranvijaysanumrepo
  template:
    metadata:
      labels:
        app: ranvijaysanumrepo 
    spec:
      containers:
        - name: ranvijaysanumrepo 
          image: mycra872.azurecr.io/ranvijaysanumrepo
          ports:
          - containerPort: 8080